---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/bills":
    get:
      summary: Lista as faturas
      tags:
      - Faturas
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                bill:
                  value:
                    status: SUCCESS
                    data:
                      value: decimal 
                      due_date: date
                      state: string
                      enrollment_id: integer
  "/api/v1/bills/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Lista uma fatura pelo id
      tags:
      - Faturas
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                bill:
                  value:
                    status: SUCCESS
                    data:
                      value: decimal 
                      due_date: date
                      state: string
                      enrollment_id: integer
  "/api/v1/enrollments":
    get:
      summary: Lista as matrículas
      tags:
      - Matrículas
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                enrollment:
                  value:
                    status: SUCCESS
                    data:
                      course_name: string
                      total_value: decimal
                      due_date: integer
                      bills_quantity: integer
                      institution_id: integer
                      student_id: integer
    post:
      summary: Cria uma matrícula
      tags:
      - Matrículas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              enrollment:
                course_name: string
                total_value: float
                due_date: integer
                bills_quantity: integer
                institution_id: integer
                student_id: integer
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                enrollment:
                  value:
                    status: SUCCESS
                    data:
                      course_name: string
                      total_value: decimal
                      due_date: integer
                      bills_quantity: integer
                      institution_id: integer
                      student_id: integer
  "/api/v1/enrollments/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Lista uma matrícula pelo id
      tags:
      - Matrículas
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                enrollment:
                  value:
                    status: SUCCESS
                    data:
                      course_name: string
                      total_value: decimal
                      due_date: integer
                      bills_quantity: integer
                      institution_id: integer
                      student_id: integer
  "/api/v1/institutions":
    get:
      summary: Lista as instituições
      tags:
      - Instituições
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                institution:
                  value:
                    status: SUCCESS
                    data:
                      name: string
                      cnpj: string
                      kind: string
    post:
      summary: Cria uma instituição
      tags:
      - Instituições
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              institution:
                      name: string
                      cnpj: string
                      kind: string 
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                institution:
                  value:
                    status: SUCCESS
                    data:
                      name: string
                      cnpj: string
                      kind: string
  "/api/v1/institutions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Lista uma instituição pelo id
      tags:
      - Instituições
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                institution:
                  value:
                    status: SUCCESS
                    data:
                      name: string
                      cnpj: string
                      kind: string
    put:
      summary: Atualiza dados de um instuição
      tags:
      - Instituições
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              institution:
                      name: string
                      cnpj: string
                      kind: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                institution:
                  value:
                    status: SUCCESS
                    data:
                      name: string
                      cnpj: string
                      kind: string
    delete:
      summary: Deleta uma instituição
      tags:
      - Instituições
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                institution:
                  value:
                    status: SUCCESS
                    data:
                      name: string
                      cnpj: string
                      kind: string
  "/api/v1/students":
    get:
      summary: Lista os estudantes
      tags:
      - Estudantes
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                student:
                  value:
                    status: SUCCESS
                    data:
                      name: string
                      cpf: string
                      gender: string
                      payment_way: string
                      birthday: date
                      cellphone: integer
    post:
      summary: Cria um estudante
      tags:
      - Estudantes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              student:
                name: string
                cpf: string
                gender: string
                payment_way: string
                birthday: date
                cellphone: integer
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                student:
                  value:
                    status: SUCCESS
                    data:
                      name: string
                      cpf: string
                      gender: string
                      payment_way: string
                      birthday: date
                      cellphone: integer
  "/api/v1/students/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Lista um estudante pelo id
      tags:
      - Estudantes
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                student:
                  value:
                    status: SUCCESS
                    data:
                      name: string
                      cpf: string
                      gender: string
                      payment_way: string
                      birthday: date
                      cellphone: integer
    put:
      summary: Atualiza dados de um estudante
      tags:
      - Estudantes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              student:
                name: string
                cpf: string
                gender: string
                payment_way: string
                birthday: date
                cellphone: integer
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                student:
                  value:
                    status: SUCCESS
                    data:
                      name: string
                      cpf: string
                      gender: string
                      payment_way: string
                      birthday: date
                      cellphone: integer
    delete:
      summary: Deleta um estudante
      tags:
      - Estudantes
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                student:
                  value:
                    status: SUCCESS
                    data:
                      name: string
                      cpf: string
                      gender: string
                      payment_way: string
                      birthday: date
                      cellphone: integer
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
